name: Backend Deployment

on:
  workflow_dispatch: 
  push:
    branches: [ main ]
    paths:
      - 'website-backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend Docker Image
        run: |
          docker build -t intuteai/website-backend:latest .

      - name: Push Backend Docker Image
        run: |
          docker push intuteai/website-backend:latest

      - name: SSH to VPS and Deploy Backend
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/website-docker
            docker-compose pull backend
            docker-compose up -d backend
